### ISSUE TITLE
Error in Acquiring Microsoft 365 title while provisioning teamsApp/extendToM365

### ISSUE THREAD

**Issue by suraj-musmade** [MicrosoftDocs/m365copilot-docs#14]
Hi everyone,

I am currently trying to create a declarative Copilot using the instructions provided in this [documentation](https://learn.microsoft.com/en-us/microsoft-365-copilot/extensibility/ttk-declarative-copilot-getting-started?tabs=windows).

I have successfully created the project, but I encounter an error at step 8 when executing the **teamsapp provision --env dev** command. For authentication, I am using an account that has Teams Admin access.

Please see the attached image for the full error message.

![Screenshot 2024-08-12 153902](https://github.com/user-attachments/assets/dfc4bf8e-79f1-42b8-b1d1-14063d2dad70)

Any help or guidance would be greatly appreciated!

Thank you!

**Comment by sebastienlevert** [comment]
Hello @suraj-musmade! Thanks for your interest in Teams Toolkit and building declarative copilots! As stated in our documentation, we are currently in private preview and only a few tenants have access to this capability. As we grow our preview towards the general availability, you will be able to use the capability when it will land in your tenant! Watch for a blog post for when this will be available.

Thanks!
